apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-nginx-deployment
  labels:
    app: simple-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-nginx
  template:
    metadata:
      labels:
        app: simple-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest

        ports:
        - containerPort: 80
      
      # VITAL: Directs the Pods to the named GKE node pool
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
